sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-jingleNodes-plugin
    all_branches: true
env:
  global:
  - secure: CsiG8e10Bg8vzZTs8H37sc1bpf0KpKFKTJwgpg1UrAMvqnTdHHwoouY59yFYk2ADzxu3zK/BVUm9ukyZsjjorURGYfPslK8NJd3aNhjOlduuhTd7bCFJANpF/ZFYY/VO2BAowA5ebuLXwRm6JvszsfJ+8dJmbu2DYBS/uImA2+iwdYdHKt+5IAySF1XU7O7a0/gXffC4p1JoCb7iuno1miBWW/GxXP9v38DvrKYUIT40lKZYDsIXnZOqp4WQa1ty7kxCfSP4sjOSFMyStoOobhw9t5rvIv00kLwEvV+S1IY1l8QrndaOxyW0GSLTezHajuqGEMRf7q7KxDq7+5l9Cw+t8x3N0U4NEwyQjiuzVvv5fPwffzNon/PFG3Z5NLN6jthvY6B2s8Y4eH0M5gNbFXy+1933XY00JfgotBHCDGzjzc9t5Kog8pT4B4ATLYMewkf76DIf8QL2utbLcJA5D9pN0RSG1bkohHR03o9gWD9oYnhLOtB3WRFkyu1WFktar+haQl21opaK1+VauWVLOFuegj55EmPuw1oq4eTskjNkQsYrQ50udLIP9FcdN6tHZDJBYz6Gu6KscmVApzV/Oy9+AZ7mm1nGnJYYowPrhyGny97/Pj7Dat5OkKLdpXt7NuVoPm92iqJ4RdqKXLgFe8cNS4BQOBmIxnzGhd0332I=
  - secure: o06Gfcqg999Olv69/A0iX3OuDhfF/m3ijYq9DJswPSJvORU2fomriY6im/BSbgH4tEd3R+jsRKUb6fsKCtI/qfvSVId7nRWfMfjUTmX7QEjT4QTSz+Z0OS66ApAcIun54mTfAx0tYIoBKOxqgKj3o/ozBiuul0QEOXJPCH43opqSmO41iEvuCtGPSfJS1BoSTYT87OGo2J3Fo9hVfotjhUv9IRx/tpEr4sjKehGMBU0q1AzTFVP9rQ6Z72MycR6ye5EpUMUgrnbzDFg1ZEyyYdJ3XE7k1WFDzfeqxVHoJMvEGxPYXiugxWJ23/rZQoFk4PlVaQdyk6Y3W4Ed9iyaf3RdkwSaSx8AnafyW3YennMnGFzsFz3nZCAYS2JkeVo7czgMkNw024FeWoUWiluyK/7Y6TnLs5QucbVhvl0ZFE+XhiF3550kcZrlJPqWbZfZ0AYv4jRM4IlYFmJMWOB33QlA6uI1pLtC1PRZl573m4PA5iWrpglPS8mgm1XONA3Z+22HrrL8dZTVa9CoRyjNH774HEpkGDfLKdpzSKwxyn2h47g7nV22kWlV27x7e9GbYR5W4L5PGCO8N51DEved8k0cJ7/1KFnk0FAnY8DHIyGXAG70+WY9C5qcn3HJbZhvSWkjZ5tqsSPsPt1IOc92fU0NirZuP1Cu8rsag8VNow0=
